Niaz erdoolatov
codify-testing-01/test-case pull request #10
Opened 2022-11-13 14:31 UTC by neojan84

little changes

2022-11-13 14:32 UTC, neojan84 commented
2 files added

2022-11-17 12:43 UTC, Pokhilenko commented on README.md
> +hello everybody 1
nice counter)

2022-11-17 12:48 UTC, Pokhilenko requested changes
Here are some changes you need to make before merging this PR to the main branch

2022-11-17 12:48 UTC, Pokhilenko commented on Niaz/testCheck.sql
> +    ORDER BY id;
Seems like `END` is missing here

2022-11-17 12:48 UTC, Pokhilenko commented on Niaz/testCheck.sql
> +    ORDER BY id;
Fix indentations all over the files, please

2022-11-17 12:48 UTC, Pokhilenko commented on Niaz/suspectInvestigation2.sql
> +OR lower(surname) not like 'Gre_n';
please, unify commands' case: make them all in lower or all in upper case

2022-11-17 12:48 UTC, Pokhilenko commented on Niaz/expressionsVerification.sql
> +CREATE PROCEDURE solution()
Move all `.sql` files to `sql-assignment` folder under the `Niaz` folder

2022-11-20 12:56 UTC, Pokhilenko commented on Niaz/testCheck.sql
> +    ORDER BY id;
Figured out, that it's okay for this assignment, no need to add `END`

2022-11-21 08:58 UTC, neojan84 commented on Niaz/testCheck.sql
> +    ORDER BY id;
fixed where needed

2022-11-21 08:59 UTC, neojan84 commented on Niaz/suspectInvestigation2.sql
> +OR lower(surname) not like 'Gre_n';
made it in upper case

2022-11-21 08:59 UTC, neojan84 commented on Niaz/expressionsVerification.sql
> +CREATE PROCEDURE solution()
Created and moved everything to a new folder.

2022-11-21 09:37 UTC, Pokhilenko approved these changes

2022-11-21 09:58 UTC, merged