Akylbek
codify-testing-01/test-case pull request #21
Opened 2022-11-20 16:40 UTC by AkylbekSeytaliev

2022-11-20 20:01 UTC, Pokhilenko requested changes
Нужны небольшие изменения

2022-11-20 20:01 UTC, Pokhilenko commented on AkylbekSeytaliev/sql-assignment/securityBreach.sql
> +	 ORDER BY attribute;
Нужно выровнять отступы

2022-11-20 20:01 UTC, Pokhilenko commented on AkylbekSeytaliev/sql-assignment/newsSubscribers.sql
> +	ORDER BY subscriber;
выровнять отступы

2022-11-21 18:57 UTC, AkylbekSeytaliev commented on AkylbekSeytaliev/sql-assignment/newsSubscribers.sql
> +	ORDER BY subscriber;
в вскоде все ровно стало теперь
криво было только Securitybreach

NewsSubscribers стоит ровно

2022-11-24 14:52 UTC, merged