Sadyk
codify-testing-01/test-case pull request #37
Opened 2022-12-09 15:07 UTC by Saadyk94

API test case

2022-12-12 14:57 UTC, Pokhilenko requested changes

2022-12-12 14:57 UTC, Pokhilenko commented on sadyk/API-assignment/API test case
> +Test scenario ID - 1
It's a good practice to provide short name to the test case/scenario

2022-12-12 14:57 UTC, Pokhilenko commented on sadyk/API-assignment/API test case
> +Test scenario ID - 1
something like "should successfully create new order"

2022-12-12 14:57 UTC, Pokhilenko commented on sadyk/API-assignment/API test case
> +  "complete": true
Would be super cool if we had some negative scenario for the request body as well, not only URL

2022-12-12 14:57 UTC, Pokhilenko commented on sadyk/API-assignment/API test case
> +3. Click "Send" button
here, within this document we assume that user is familiar with postman, so we can remove extra steps like "Select RAW", "select GET", "click send" etc.

e.g. here we can make it using single step "Send GET request to https://petstore.swagger.io/v2/store/order/10 using Postman"

2022-12-12 14:57 UTC, Pokhilenko commented on sadyk/API-assignment/API test case
> +
too many blank lines, 2 would be enough

2022-12-12 14:57 UTC, Pokhilenko commented on sadyk/API-assignment/API test case
> +Expected result: Status 200 OK
I believe there is also a response body expected, not only the status

2022-12-14 09:50 UTC, Pokhilenko commented on sadyk/API-assignment/API test case.txt
> +    "code": 404,
`{` is missing

2023-01-12 07:46 UTC, Saadyk94 reviewed
done

2023-01-12 07:52 UTC, Saadyk94 commented on sadyk/API-assignment/API test case.txt
> +    "code": 404,
done

2023-01-12 07:52 UTC, Saadyk94 commented on sadyk/API-assignment/API test case.txt
> +    "code": 404,
done

2023-01-12 13:16 UTC, merged