Niaz erdoolatov
codify-testing-01/test-case pull request #40
Opened 2022-12-14 16:14 UTC by neojan84

Swagger Petstore API

2022-12-19 15:18 UTC, Pokhilenko requested changes
Overall is good, but, please, make it little bit prettier and more readable by playing with .md styling.

2022-12-19 15:18 UTC, Pokhilenko commented on api-assignment/petStoreAPITests1.md
> +---post---
I see **post**, where is the **get**?

2022-12-19 15:18 UTC, Pokhilenko commented on api-assignment/petStoreAPITests1.md
> +For testing these scenarios we will need:
Before writing actual test scenarios and steps it's better to add some title like "Pet Store API - Order"

2022-12-19 15:18 UTC, Pokhilenko commented on api-assignment/petStoreAPITests1.md
> +Scenario/Case 1 - Create store order
Since you're using .md you can make it much more prettier by prefixing `####` for example

2022-12-19 15:21 UTC, Pokhilenko commented
resolve conflicts before merging and remove all the files which are not related to your current task

2022-12-20 05:39 UTC, neojan84 commented
I've deleted all the irrelevant files

2022-12-25 15:17 UTC, closed without merging